linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3

  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
        arguments:
          - allowRegex: "^_|^tx$"

linters:
  disable-all: true
  enable:
    - bodyclose
    - unused
    - errcheck
    - exportloopref
    - goconst
    - gofmt
    - goimports
    - gocyclo
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unused
    - typecheck
    - unconvert
    - unparam
    - unused

run:
  issues-exit-code: 1
