# fly.toml app configuration file generated for photopost-460850 on 2024-08-04T22:21:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'photopost-460850'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
